### ISSUE TITLE
Server not generating biomes o plenty

### ISSUE THREAD

**Issue by Vidicon** [scalda/Foolcraft_3#16]
After installing the server from https://minecraft.curseforge.com/projects/foolcraft-3/files/2562992#additional-files I have a default world after generating the world. In server.properties 'leve-type' is set to 'BIOMESOP'. 
Did I forget something?

**Comment by Mrbysco** [comment]
Could you provide more information?
Server log?

**Comment by Vidicon** [comment]
Do you mean this:
`[17:46:58] [Server thread/INFO]: Starting minecraft server version 1.12.2
[17:46:58] [Server thread/INFO]: Loading properties
[17:46:58] [Server thread/INFO]: Default game type: SURVIVAL
[17:46:58] [Server thread/INFO]: Generating keypair
[17:46:58] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:25565
OpenJDK Server VM warning: You have loaded library /tmp/libnetty-transport-native-epoll5988468920756283854.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
[17:46:58] [Server thread/INFO]: Using default channel type
[17:46:59] [Server thread/INFO]: Preparing level "FoolCraft3"
[17:47:00] [Server thread/INFO]: Loaded 488 advancements
[17:47:01] [Server thread/INFO]: Preparing start region for level 0
[17:47:02] [Server thread/INFO]: Preparing spawn area: 4%
[17:47:03] [Server thread/INFO]: Preparing spawn area: 6%
[17:47:04] [Server thread/INFO]: Preparing spawn area: 8%
[17:47:05] [Server thread/INFO]: Preparing spawn area: 10%
[17:47:06] [Server thread/INFO]: Preparing spawn area: 12%
[17:47:07] [Server thread/INFO]: Preparing spawn area: 14%
[17:47:08] [Server thread/INFO]: Preparing spawn area: 17%
[17:47:09] [Server thread/INFO]: Preparing spawn area: 20%
[17:47:10] [Server thread/INFO]: Preparing spawn area: 22%
[17:47:12] [Server thread/INFO]: Preparing spawn area: 25%
[17:47:13] [Server thread/INFO]: Preparing spawn area: 28%
[17:47:14] [Server thread/INFO]: Preparing spawn area: 31%
[17:47:15] [Server thread/INFO]: Preparing spawn area: 34%
[17:47:16] [Server thread/INFO]: Preparing spawn area: 37%
[17:47:17] [Server thread/INFO]: Preparing spawn area: 41%
[17:47:18] [Server thread/INFO]: Preparing spawn area: 43%
[17:47:19] [Server thread/INFO]: Preparing spawn area: 46%
[17:47:20] [Server thread/INFO]: Preparing spawn area: 50%
[17:47:21] [Server thread/INFO]: Preparing spawn area: 53%
[17:47:22] [Server thread/INFO]: Preparing spawn area: 56%
[17:47:23] [Server thread/INFO]: Preparing spawn area: 59%
[17:47:24] [Server thread/INFO]: Preparing spawn area: 63%
[17:47:25] [Server thread/INFO]: Preparing spawn area: 68%
[17:47:26] [Server thread/INFO]: Preparing spawn area: 72%
[17:47:27] [Server thread/INFO]: Preparing spawn area: 76%
[17:47:28] [Server thread/INFO]: Preparing spawn area: 81%
[17:47:29] [Server thread/INFO]: Preparing spawn area: 85%
[17:47:30] [Server thread/INFO]: Preparing spawn area: 89%
[17:47:31] [Server thread/INFO]: Preparing spawn area: 95%
[17:47:32] [Server thread/INFO]: Done (33.271s)! For help, type "help" or "?"
[17:47:32] [Server thread/INFO]: Starting GS4 status listener
[17:47:32] [Query Listener #1/INFO]: Query running on 0.0.0.0:25565
`

I'm running the server on Ubuntu server 16.04

**Comment by Mrbysco** [comment]
Are you running the forge-1.12.2-14.23.3.2673-universal.jar or the minecraft_server.1.12.2.jar? as you should be running the forge one.

**Comment by Vidicon** [comment]
after generating a world in singleplayer and using it for the server I get This:
`[18:02:50] [Server thread/WARN]: Skipping BlockEntity with id minecraft:tilechancecube
[18:02:50] [Server thread/WARN]: Skipping BlockEntity with id minecraft:tilechancecube
[18:02:50] [Server thread/WARN]: Ignoring unknown attribute 'tc.mobmod'
[18:02:50] [Server thread/WARN]: Ignoring unknown attribute 'tc.mobmodtaint'
[18:02:50] [Server thread/WARN]: Ignoring unknown attribute 'tc.mobmod'
[18:02:50] [Server thread/WARN]: Ignoring unknown attribute 'tc.mobmodtaint'
[18:02:50] [Server thread/WARN]: Ignoring unknown attribute 'tc.mobmod'
[18:02:50] [Server thread/WARN]: Ignoring unknown attribute 'tc.mobmodtaint'
`
it seems that the server did not load the mods.

**Comment by Vidicon** [comment]
I was running the minecraft_server.1.12.2.jar as the forge-1.12.2-14.23.3.2673-universal.jar gave this:
`A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62)
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31)
Caused by: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 6 more
`

**Comment by Vidicon** [comment]
`vidicon@vidicon-PE60-2QE:~/Downloads/server$ java -version
openjdk version "10.0.1" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)

`

**Comment by Vidicon** [comment]
I think it is now working on my server. (but not on my laptop (running Ubuntu 18.04))

**Comment by Vidicon** [comment]
Laptop:
`vidicon@vidicon-PE60-2QE:~/Downloads/server$ java -version
openjdk version "10.0.1" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)
`
server:
`mcserver@mcserver:~$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK Server VM (build 25.171-b11, mixed mode)
`
server is now running as expected. 
thank you
