### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by stolenwhisper** [scalda/Foolcraft_3#248]
## Issue Description
Exception in server tick loop crash. Happens when last player disconnects. Unknown, see log.

## Reproduce Steps
Last client disconnects.

## Additional Information
Added Mods: VivecraftForgeExtensions-1.12.2-0.2.4.12.jar.

Note: This was not a vivecraft player this is happening to.

https://pastebin.com/GzNpXB0d

**Comment by stolenwhisper** [comment]
Update: Seems to have happend when the server tried to create a backup.

[01:06:08] [Server thread/INFO] [FTB Utilities]: Server Backup started!
[01:06:08] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_181]
	at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_181]
	at java.util.AbstractCollection.addAll(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111122_c(SourceFile:62) ~[wh.class:?]
	at net.minecraft.network.play.server.SPacketEntityProperties.<init>(SourceFile:26) ~[kv.class:?]
	at net.minecraft.entity.EntityTrackerEntry.func_111190_b(EntityTrackerEntry.java:327) ~[os.class:?]
	at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:273) ~[os.class:?]
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:292) ~[ol.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:779) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
[01:06:08] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: C:\Game Servers\FoolCraft 3\.\crash-reports\crash-2018-07-28_01.06.08-server.txt

**Comment by scalda** [comment]
Please post the crash report that was created

**Comment by scalda** [comment]
closeing as there has been no response
