### ISSUE TITLE
Server not Launching

### ISSUE THREAD

**Issue by Dazzah** [scalda/Foolcraft_3#82]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
Got a bit of a problem with my server, I can launch the minecraft_server_1.12.2.jar fine, but i can't launch the forge server.
It doesn't print out an error log or anything, but upon creating a pause in a .bat this is what it has:

A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31)
Caused by: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
Press any key to continue . . .

Can someone help with that?

## Reproduce Steps
I can reproduce itt myself by trying to launch the forge-1.12.2-14.23.3.2673-universal.jar

## Additional Information
[https://imgur.com/6q2fILQ](https://imgur.com/6q2fILQ)

**Comment by Mrbysco** [comment]
Java version?

**Comment by scalda** [comment]
no response in the last 7 days so i am closing
